name: check code
on: [push]
jobs:
    check-for-linting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pylint
                pip install pyTelegramBotAPI
            - name: Analysing the code with pylint
              run: |
                pylint `ls -R |grep .py$ | xargs`
    check-dockerfile:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Try build the Docker image
              run: docker build . --file Dockerfile --tag eval-bot:$(date +%s)
    bot-functions-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                python-version: 3.9
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
                pip install pyTelegramBotAPI
            - name: Run tests
              run: pytest